### ISSUE TITLE
Possible bug? No notes longer than about 3 seconds in duration when using Soundfont

### ISSUE THREAD

**Issue by drscottlobo** [danigb/smplr#23]
Hi @danigb ! 

OK, I just ran into something strange, I was playing some long tones against a metronome click at 60BPM, currently using any instrument in the soundfonts list that's capable of a long tone, I've tried several, but right now I'm using "drawbar_organ." But for some reason, nothing will last longer than about 3.5 seconds, it cuts off there every time, and with every instrument I load from the default set. I'm not sure why it won't play a note any longer than that? Is that just a limitation of those sample libraries?

Here's a basic mock-up: 

```
const ctx = new AudioContext()
const organ = await new Soundfont(ctx, {instrument: 'drawbar_organ').loaded();

organ.start({note: 'C4', time: 0, duration: 5}) /// always cuts off at around 3.5 seconds

```
Are you getting the same behavior? Any reason why the sample won't go above that duration? 

Thanks for any help!

**Comment by danigb** [comment]
Hello, 

Yes, looping samples are not supported right now. Basically, in order to make a long sound you need:
1. Play the initial part of the sample
2. Loop the middle part while the key is pressed (aka: until stop event)
3. Play the last part of the sample, or something similar, to simulate a longer release

Sampler file formats used include the "loop" timing information for each sample in order to do so, but as far as I know, that information is not in the soundfont.js file (where we get samples from).
I could try to implement something that simulates that behaviour, but not sure if will be good enough to use...

**Comment by drscottlobo** [comment]
Ok. No worries! Thanks!_______________Scott Wolf, DMAOxnard College - Professor of MusicOn May 26, 2023, at 8:23 AM, danigb ***@***.***> wrote:﻿
Hello,
Yes, looping samples are not supported right now. Basically, in order to make a long sound you need:

Play the initial part of the sample
Loop the middle part while the key is pressed (aka: until stop event)
Play the last part of the sample, or something similar, to simulate a longer release

Sampler file formats used include the "loop" timing information for each sample in order to do so, but as far as I know, that information is not in the soundfont.js file (where we get samples from).
I could try to implement something that simulates that behaviour, but not sure if will be good enough to use...

**Comment by goldst** [comment]
@drscottlobo thanks for bringing this up, I had exactly the same problem the other day.

@danigb I did some experimentation on this. [My fork of Midi.js now contains the missing loop data in separate files](https://github.com/gleitz/midi-js-soundfonts/compare/gh-pages...goldst:midi-js-soundfonts:feature/loop) as well as [instructions and a script to generate the loop data](https://github.com/goldst/midi-js-soundfonts/blob/feature/loop/generate-loop-data.js). The data seems to be somewhat incomplete for now, but I was able to confirm that it seems to partially work when smplr is slightly adjusted. I tested it with the Musyng Cello. For my test, I added `source.loop = true` after [this line](https://github.com/danigb/smplr/blob/d60b7d554dc2c42df9947ddbd22cec6935955e9e/src/sampler/start-sample.ts#L86) and sliced the AudioBuffer using a modified version of [this code snippet](https://miguelmota.com/bytes/slice-audiobuffer/) after [this line](https://github.com/danigb/smplr/blob/d60b7d554dc2c42df9947ddbd22cec6935955e9e/src/soundfont/soundfont.ts#L62).

Are you interested in implementing a loop feature? If yes, I'm open on putting my fork on github pages so you can fetch the data. Feel free to request changes to the format. Alternatively, because I am converting the sf2 files to sfz for the generation of the loop data, it might make more sense to read the loop information directly from (web)sfz files. What do you think?

**Comment by danigb** [comment]
Wow, @goldst definitely interested. If you serve the files on github, I'll implement that on this library 👍  Thanks for keeping an eye on this 👁️

**Comment by drscottlobo** [comment]
Thanks @goldst Excited to try it out!

**Comment by FredericoGauz** [comment]
Hi all, I was having the same issue and you can imagine how glad I was to find this issue! =)

I would be happy to implement this fix, but since I am new to this kind of sound libraries it would be great to get some pointers.

@goldst would you be able to help me with that?

Thanks in advance!

**Comment by goldst** [comment]
Great, @FredericoGauz! Probably @danigb can give you better pointers because I don't really have experience with these kinds of sound libraries either. There also was some activity in the repo in June, so maybe you two should ensure that you're not implementing the same thing simultaneously. I would probably try to do the following:

1. Try to recreate what I did [here](https://github.com/danigb/smplr/issues/23#issuecomment-1566759981). I'm afraid I don't have my code for that anymore, unfortunately. You can clone this repo, create a small separate example project and install your cloned version in the example project using `npm link`. The code snippet that I refer to in my comment takes in ms and if I recall correctly my data is in frames, so you need to change a few lines slightly. Also, there is a callback thing that you can remove, I think. You don't need my URL for this part yet.
2. See if you can replace the previous URL [here](https://github.com/danigb/smplr/blob/49a8b5a942242a78ceb944459af06e8521c43558/src/soundfont/soundfont.ts#L96) with mine. If everything works, it shouldn't change anything.
3. You could then come up with a similar function to get the JSON files that I added to my version.
4. The numbers in the JSON files describe the start and end of part 2 from @danigb's [list](https://github.com/danigb/smplr/issues/23#issuecomment-1564555059). You should be able to pass them in as parameters to the function from step 1.
5. This is the part where I am not sure either how to accomplish it: you need to play parts 1 and 3 without looping before/after part 2. Maybe you can find something in the [mdn web docs for AudioBuffer](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer) or the Web Audio API in general

Just a short note, I didn't really test that the data in my json files is correct. So if it doesn't work, that's not necessarily on your end. Let me know in that case :)

**Comment by danigb** [comment]
Hi, just a quick note to say that I didn't have time to start the implementation, so very open to PRs 👍

**Comment by FredericoGauz** [comment]
Hi Leonard and @danigb,

Thanks for the explanations, I managed to link the lib locally a few days
ago but got sick this week. I will see if I can work on the loop issue in
the next days or weekend.

Thanks for the detailed explanations Leonard, I hope I will manage to add
this feature.

I am also keen on exposing some of the web audio api to the user, because I
need to have a bit more control on the audio produced. Is that something
that you also would be keen danigb?

**Comment by FredericoGauz** [comment]
Just a quick update, yesterday I decided not to keep working with this directly with this library but to integrate the soundfont playback in my project.

I want however to enable longer notes and when I figure out how to do it I will update this thread.

Thanks everyone!

**Comment by FredericoGauz** [comment]
By the way, @goldst , you mentioned that you changed the soundfonts data as well, but I couldn't find them. I tested the intervals with the data I have (on piccolo) but it does not seems to be fitting very well.

**Comment by danigb** [comment]
Hi all. A first implementation of Soundfont loops is live. Unfortunately it doesn't sound very good. You can try it on the [demo](https://danigb.github.io/smplr/) or read the [docs](https://github.com/danigb/smplr#looping).

Possible improvements:
- Inspect quality of the data. Ensure that the sampled points are correct (to me, some loops are too small)
- Process buffers to create cross fades. Not sure if it's a good idea
Ideas welcomed

![Screenshot 2023-09-15 at 17 01 45](https://github.com/danigb/smplr/assets/7457/84d2e2a8-e2aa-47b8-a728-65e5af064c69)

**Comment by goldst** [comment]
@FredericoGauz Sorry for the late reply, I wanted to check that but didn't have the time yet.

@danigb Awesome, thank you! I'll check what causes the problem - if it's my numbers and there is a way to fix it, I'll update them.

**Comment by henrikvilhelmberglund** [comment]
I'm also interested in looping. I think the loops are defined in the soundfonts, however each sample has its own loop points basically. I checked this in polyphone: 
![image](https://github.com/danigb/smplr/assets/110549389/a066cd71-289c-4b3b-a549-18c5ab639185)

Anything new on this front? 😊

**Comment by danigb** [comment]
That should be working: https://github.com/danigb/smplr#soundfont-sustained-notes
Give it a try and if you have specific question or suggestion, I'm all ears 👂
